# -*- coding: utf-8 -*-
"""Ip_check_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17afaH_etpK0nMRkl9Df2s0mzYycIMNY7
"""

# Set your Git config (run only once per session)
!git config --global user.email "saikavuturi24@gmail.com"
!git config --global user.name "Sairupesh24"

!git clone https://github.com/Sairupesh24/IP_Check_app.git

code = '''
from flask import Flask, request, redirect, make_response

app = Flask(__name__)

ALLOWED_IP = "183.82.122.72"
GOOGLE_FORM_URL = "https://forms.gle/hwDy6VZb3BA8TM18A"

@app.route("/")
def home():
    if request.headers.getlist("X-Forwarded-For"):
        ip = request.headers.getlist("X-Forwarded-For")[0].split(',')[0]
    else:
        ip = request.remote_addr

    if ip == ALLOWED_IP:
        return redirect(GOOGLE_FORM_URL, code=302)
    else:
        html = f"""
        <html>
            <body style="font-family: Arial; text-align: center; margin-top: 100px;">
                <h2>Access Denied</h2>
                <p>This form is only available on the authorized Wi-Fi network.</p>
                <p>Your IP: {ip}</p>
            </body>
        </html>
        """
        response = make_response(html)
        return response

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=3000)
'''
with open("/content/IP_Check_app/app.py", "w") as f:
    f.write(code)
